// Code generated by scripts/generate_tui_protocol.py; DO NOT EDIT.
package protocol

import "encoding/json"

const GeneratedVersion = 8

type CommandRequest struct {
	Command string         `json:"command"`
	Payload map[string]any `json:"payload"`
}

type CommandError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
}

type CommandResult struct {
	OK      bool            `json:"ok"`
	Command string          `json:"command"`
	Result  json.RawMessage `json:"result"`
	Error   *CommandError   `json:"error"`
}
