"""Generate checked-in protocol v8 artifacts from the Pydantic source of truth."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from strix.interface.tui.backend.protocol import PROTOCOL_VERSION, protocol_json_schema


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "strix" / "interface" / "tui" / "protocol-v8.schema.json"
GO_PATH = ROOT / "strix" / "interface" / "tui" / "internal" / "protocol" / "commands_v8.go"


def outputs() -> dict[Path, str]:
    schema = json.dumps(protocol_json_schema(), indent=2, sort_keys=True) + "\n"
    go = f"""// Code generated by scripts/generate_tui_protocol.py; DO NOT EDIT.
package protocol

import "encoding/json"

const GeneratedVersion = {PROTOCOL_VERSION}

type CommandRequest struct {{
\tCommand string         `json:"command"`
\tPayload map[string]any `json:"payload"`
}}

type CommandError struct {{
\tCode      string `json:"code"`
\tMessage   string `json:"message"`
\tRetryable bool   `json:"retryable"`
}}

type CommandResult struct {{
\tOK      bool            `json:"ok"`
\tCommand string          `json:"command"`
\tResult  json.RawMessage `json:"result"`
\tError   *CommandError   `json:"error"`
}}
"""
    return {SCHEMA_PATH: schema, GO_PATH: go}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale: list[str] = []
    for path, content in outputs().items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        parser.error("generated protocol artifacts are stale: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
